### ISSUE TITLE
Does not work with corail tombstone mod.

### ISSUE THREAD

**Issue by agentwolf88** [FirEmerald/DynamicVerticalSlabsAndStairs#1] opened 2022-09-18 10:08 UTC
[crash-2022-09-18_12.06.15-fml.txt](https://github.com/FirEmerald/DynamicVerticalSlabsAndStairs/files/9593708/crash-2022-09-18_12.06.15-fml.txt)

**Comment by FirEmerald** [comment] 2022-09-18 14:48
this seems to be caused by the mod using an object holder reference when constructing its stairs, I'll have to modify how vertical stairs handle themselves to account for mods that do that. Thanks for pointing it out!

**Comment by FirEmerald** [comment] 2022-09-18 16:11
Fixed as of [8000e977e9bd13dca89f01b4b372042fdacc2633](https://github.com/FirEmerald/DynamicVerticalSlabsAndStairs/commit/8000e977e9bd13dca89f01b4b372042fdacc2633)

**Closed by FirEmerald** 2022-09-18 16:11 UTC
